server:
  port: 10010 # 网关端口

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: dev
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: order-service # 路由id，自定义，只要唯一即可
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=origin, gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.alibaba.nacos: DEBUG


