server:
  port: 8083

spring:
  application:
    name: orderservice
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: mredust4
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        # 限流规则
        flow:
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 还可以是：degrade、authority、param-flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: orderservice-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade


# 降级
feign:
  sentinel:
    enabled: true


seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
      context-path: ""
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  data-source-proxy-mode: XA
  # 拉取seata配置
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: 'SEATA_GROUP'
#      namespace: ''
#      dataId: 'seataServer.properties'
#      username: 'nacos'
#      password: 'nacos'

mybatis-plus:
  type-aliases-package: com.mredust.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出详细日志
  global-config:
    banner: false #控制台忽略启动图标

