server:
  port: 8084

spring:
  application:
    name: storage-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: mredust4
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
      context-path: ""
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  data-source-proxy-mode: XA


mybatis-plus:
  type-aliases-package: com.mredust.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出详细日志
  global-config:
    banner: false #控制台忽略启动图标